"use client";

import { useRef, useState } from "react";
import { Camera, CircleStop, Upload, Video } from "lucide-react";

export default function VideoPage(){
  const videoRef=useRef<HTMLVideoElement>(null); const recorderRef=useRef<MediaRecorder|null>(null); const streamRef=useRef<MediaStream|null>(null); const chunks=useRef<Blob[]>([]);
  const [recording,setRecording]=useState(false); const [preview,setPreview]=useState<string|null>(null); const [error,setError]=useState("");
  async function start(){try{setError("");const stream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play()}const recorder=new MediaRecorder(stream);chunks.current=[];recorder.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);recorder.onstop=()=>{const blob=new Blob(chunks.current,{type:recorder.mimeType||"video/webm"});setPreview(URL.createObjectURL(blob));stream.getTracks().forEach(t=>t.stop())};recorderRef.current=recorder;recorder.start();setRecording(true)}catch(e){setError(e instanceof Error?e.message:"Camera access failed")}}
  function stop(){recorderRef.current?.stop();setRecording(false);streamRef.current?.getTracks().forEach(t=>t.stop())}
  return <main style={{minHeight:"100vh",padding:"40px 20px"}}><div style={{maxWidth:900,margin:"auto"}}><div className="eyebrow">VIDEO ANALYSIS</div><h1 style={{fontSize:42,letterSpacing:"-.05em",margin:"8px 0"}}>Record your movement.</h1><p style={{color:"var(--muted)",maxWidth:620}}>The browser records the exercise first. Pose estimation, rep counting and form scoring should run asynchronously after upload.</p><div className="card" style={{marginTop:25}}><div style={{aspectRatio:"16/9",background:"#050608",borderRadius:12,overflow:"hidden",display:"grid",placeItems:"center"}}>{preview?<video src={preview} controls style={{width:"100%",height:"100%",objectFit:"contain"}}/>:<video ref={videoRef} muted playsInline style={{width:"100%",height:"100%",objectFit:"cover"}}/>}</div>{error&&<p style={{color:"var(--red)",fontSize:12}}>{error}</p>}<div style={{display:"flex",gap:10,marginTop:16}}>{!recording?<button className="primary" onClick={start}><Camera size={16}/> Record video</button>:<button className="primary" onClick={stop}><CircleStop size={16}/> Stop recording</button>}<label className="icon-btn" style={{width:"auto",padding:"0 14px",gap:8,display:"flex",cursor:"pointer"}}><Upload size={16}/> Upload<input type="file" accept="video/*" style={{display:"none"}} onChange={e=>{const f=e.target.files?.[0];if(f)setPreview(URL.createObjectURL(f))}}/></label></div></div><div className="card coach" style={{marginTop:15}}><b><Video size={15}/> Capture checklist</b><p style={{color:"var(--muted)",fontSize:12,marginBottom:0}}>Full body visible · stable camera · good lighting · enough distance · one exercise per clip. Form feedback is fitness guidance, not medical diagnosis.</p></div></div></main>
}
