"use client";

import { useMemo, useState } from "react";
import { Activity, BarChart3, Bell, CalendarDays, Camera, Check, ChevronRight, Dumbbell, Flame, Home, LogOut, Menu, MessageCircle, Play, Settings, ShieldCheck, Sparkles, Target, Timer, Trophy, UserRound, Utensils, X } from "lucide-react";

type View = "dashboard" | "training" | "skills" | "progress" | "nutrition" | "profile";

const nav: {id:View;label:string;icon:typeof Home}[] = [
  {id:"dashboard",label:"Dashboard",icon:Home}, {id:"training",label:"Training",icon:Dumbbell}, {id:"skills",label:"Skills",icon:Target},
  {id:"progress",label:"Progress",icon:BarChart3}, {id:"nutrition",label:"Nutrition",icon:Utensils}, {id:"profile",label:"Profile",icon:UserRound}
];

const exercises = [
  ["Push-ups","3 × 12","RPE 7"],["Incline dumbbell press","3 × 10","RPE 7"],["Dumbbell shoulder press","3 × 10","RPE 7"],["Assisted dip","3 × 8","RPE 8"],["Lateral raise","3 × 15","Controlled"],["Hollow hold","3 × 30s","Core"]
];

const skills = [
  ["Push-up","100%","Unlocked"],["Pull-up","62%","Next: controlled negatives"],["L-sit","38%","Next: tuck hold"],["Handstand","22%","Next: wall hold"],["Muscle-up","12%","Long-term target"]
];

function Stat({label,value,sub,icon:Icon}:{label:string;value:string;sub:string;icon:typeof Activity}){return <div className="card metric-card"><div className="metric-top"><span>{label}</span><Icon size={16}/></div><div><div className="metric-value">{value}</div><div className="metric-sub">{sub}</div></div></div>}

export default function HomePage(){
  const [view,setView]=useState<View>("dashboard");
  const [assessment,setAssessment]=useState(false);
  const [coach,setCoach]=useState(false);
  const [completed,setCompleted]=useState<number[]>([]);
  const [seconds,setSeconds]=useState(90);
  const [running,setRunning]=useState(false);
  const [mobile,setMobile]=useState(false);

  useMemo(()=>{ if(!running)return; const id=window.setInterval(()=>setSeconds(s=>s>0?s-1:90),1000); return ()=>window.clearInterval(id); },[running]);
  const time=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
  const title=nav.find(n=>n.id===view)?.label ?? "Dashboard";

  const completeSet=(i:number)=>setCompleted(v=>v.includes(i)?v.filter(x=>x!==i):[...v,i]);

  return <div className="app-shell">
    <aside className="sidebar">
      <div className="logo"><div className="logo-mark">C</div><span>CALISTHENICS AI</span></div>
      <div className="nav">{nav.map(n=>{const I=n.icon;return <button key={n.id} className={view===n.id?"active":""} onClick={()=>setView(n.id)}><I size={17}/><span>{n.label}</span></button>})}</div>
      <div className="side-bottom"><div className="mini-profile"><div className="avatar">A</div><div><b>Abhishek</b><small>Personal plan</small></div></div></div>
    </aside>

    <main className="main">
      <header className="topbar"><div style={{display:"flex",alignItems:"center",gap:10}}><button className="icon-btn mobile-menu" onClick={()=>setMobile(v=>!v)}><Menu size={18}/></button><h1>{title}</h1></div><div className="top-actions"><button className="icon-btn" onClick={()=>setCoach(true)}><MessageCircle size={17}/></button><button className="icon-btn"><Bell size={17}/></button></div></header>
      {mobile && <div style={{position:"fixed",top:72,left:0,right:0,zIndex:50,padding:12,background:"#0d0f12",borderBottom:"1px solid var(--line)"}}>{nav.map(n=><button key={n.id} onClick={()=>{setView(n.id);setMobile(false)}} style={{display:"block",width:"100%",padding:12,textAlign:"left",background:"transparent",border:0,color:"white"}}>{n.label}</button>)}</div>}

      <div className="content view">
        {view==="dashboard" && <Dashboard onAssessment={()=>setAssessment(true)} onStart={()=>setView("training")} onCoach={()=>setCoach(true)}/>} 
        {view==="training" && <Training completed={completed} onComplete={completeSet} time={time} running={running} onRun={()=>setRunning(v=>!v)} />}
        {view==="skills" && <Skills/>}
        {view==="progress" && <Progress/>}
        {view==="nutrition" && <Nutrition/>}
        {view==="profile" && <Profile onAssessment={()=>setAssessment(true)}/>} 
      </div>
    </main>

    {assessment && <Assessment onClose={()=>setAssessment(false)} onDone={()=>{setAssessment(false);setView("dashboard")}}/>}
    {coach && <Coach onClose={()=>setCoach(false)}/>} 
  </div>
}

function Dashboard({onAssessment,onStart,onCoach}:{onAssessment:()=>void;onStart:()=>void;onCoach:()=>void}){return <>
  <div className="hero-row"><div><div className="eyebrow">PERSONAL COACH · TODAY</div><h2>Good afternoon, Abhishek.</h2><p>Your plan adapts around your goals, equipment, history and recovery.</p></div><button className="primary" onClick={onAssessment}>Update assessment</button></div>
  <div className="grid grid-4"><Stat label="CURRENT STREAK" value="12 days" sub="Best: 24 days" icon={Flame}/><Stat label="WEEKLY TARGET" value="4 / 5" sub="80% completed" icon={CalendarDays}/><Stat label="CALISTHENICS SCORE" value="67 / 100" sub="+8 this month" icon={Trophy}/><Stat label="RECOVERY" value="78%" sub="Normal session" icon={Activity}/></div>
  <div className="section-title"><h3>Today's training</h3><span>45–60 min · Push + Core</span></div>
  <div className="grid grid-2"><div className="card workout-card"><div><div className="eyebrow">WEEK 4 · SESSION 2</div><h3>Push + Core</h3><p style={{color:"var(--muted)",fontSize:13,margin:0}}>6 exercises · progressive overload · RPE-guided</p><div className="exercise-list">{exercises.slice(0,4).map((e,i)=><div className="exercise" key={e[0]}><div><div className="exercise-name">{e[0]}</div><div className="exercise-meta">{e[1]} · {e[2]}</div></div><span className="chip">Ready</span></div>)}</div></div><button className="primary" onClick={onStart}><Play size={15} fill="currentColor"/> Start workout</button></div>
  <div className="card coach"><div className="eyebrow">AI COACH</div><div className="coach-message"><div className="coach-icon"><Sparkles size={18}/></div><div><p><strong>Your next best action:</strong> complete today's Push + Core session. Your recent performance supports progressing volume before changing the movement.</p><button className="primary" style={{marginTop:14,padding:"9px 12px"}} onClick={onCoach}>Ask Coach <ChevronRight size={14}/></button></div></div><div className="goal"><div><small>Next skill target</small><strong>3 controlled negatives</strong></div><Target size={28} color="var(--lime)"/></div></div></div>
  <div className="section-title"><h3>Progress snapshot</h3><span>Last 12 weeks</span></div><div className="grid grid-3"><div className="card"><div className="metric-top"><span>PUSH-UPS</span><span className="positive">+25%</span></div><div className="metric-value">15 reps</div><div className="chart">{[38,44,52,49,61,58,70,66,76,82,88,94].map((h,i)=><span className="chart-bar" style={{height:`${h}%`}} key={i}/>)}</div><div className="chart-labels"><span>JUN</span><span>JUL</span><span>AUG</span></div></div><div className="card"><div className="metric-top"><span>SKILL TREE</span><span className="positive">2 unlocked</span></div>{skills.slice(0,3).map(s=><div className="skill" key={s[0]}><div className="skill-head"><b>{s[0]}</b><span>{s[1]}</span></div><div className="bar"><span style={{width:s[1]}}/></div></div>)}</div><div className="card"><div className="metric-top"><span>RECENT ACTIVITY</span><span>THIS WEEK</span></div>{["Push + Core","Pull + Skill","Recovery","Legs + Core"].map((x,i)=><div className="skill" key={x}><div className="skill-head"><b>{x}</b><span>{i<3?"Completed":"Tomorrow"}</span></div></div>)}</div></div>
</>}

function Training({completed,onComplete,time,running,onRun}:{completed:number[];onComplete:(i:number)=>void;time:string;running:boolean;onRun:()=>void}){return <><div className="hero-row"><div><div className="eyebrow">WEEK 4 / SESSION 2</div><h2>Push + Core</h2><p>Log every set. The next session will use your performance to adapt the prescription.</p></div><div style={{display:"flex",gap:10}}><button className="icon-btn"><Camera size={17}/></button><button className="primary">Finish workout</button></div></div><div className="grid grid-2"><div className="card"><div className="metric-top"><span>SESSION TIMER</span><span>RPE GUIDED</span></div><div className="metric-value" style={{fontSize:42}}>{time}</div><button className="primary" onClick={onRun}>{running?"Pause timer":"Start rest timer"}</button></div><div className="card coach"><div className="eyebrow">SESSION NOTE</div><p style={{margin:0,color:"var(--muted)",fontSize:13,lineHeight:1.7}}>Keep 1–3 reps in reserve on strength work. If technique breaks down, stop the set rather than chasing a number.</p></div></div><div className="section-title"><h3>Exercise log</h3><span>{completed.length} sets completed</span></div><div className="card">{exercises.map((e,i)=><div className="exercise" style={{marginBottom:8}} key={e[0]}><div><div className="exercise-name">{i+1}. {e[0]}</div><div className="exercise-meta">{e[1]} · target {e[2]}</div></div><button className={completed.includes(i)?"primary":"icon-btn"} onClick={()=>onComplete(i)}>{completed.includes(i)?<Check size={16}/>:<ChevronRight size={16}/>}</button></div>)}</div></>}

function Skills(){return <><div className="hero-row"><div><div className="eyebrow">ADAPTIVE SKILL COACH</div><h2>Earn the next level.</h2><p>Progressions unlock from measurable requirements, not arbitrary AI guesses.</p></div></div><div className="grid grid-2"><div className="card"><div className="eyebrow">PULL JOURNEY</div>{[["Dead hang",100],["Scapular pull",100],["Controlled negative",78],["Assisted pull-up",64],["Strict pull-up",24],["Explosive pull-up",8],["Muscle-up",0]].map(([n,v])=><div className="skill" key={String(n)}><div className="skill-head"><b>{n}</b><span>{v}%</span></div><div className="bar"><span style={{width:`${v}%`}}/></div></div>)}</div><div className="card coach"><div className="eyebrow">NEXT UNLOCK</div><h3 style={{fontSize:26,margin:"8px 0"}}>3 controlled negatives × 8 sec</h3><p style={{color:"var(--muted)",fontSize:13}}>Complete the target with clean control. The progression engine will then reassess your pull-up readiness.</p><button className="primary">Test skill</button></div></div><div className="section-title"><h3>All skill tracks</h3><span>5 active goals</span></div><div className="grid grid-3">{skills.map(s=><div className="card" key={s[0]}><div className="metric-top"><span>{s[0].toUpperCase()}</span><span>{s[1]}</span></div><div className="bar" style={{margin:"22px 0 14px"}}><span style={{width:s[1]}}/></div><div style={{fontSize:11,color:"var(--muted)"}}>{s[2]}</div></div>)}</div></>}

function Progress(){return <><div className="hero-row"><div><div className="eyebrow">PROGRESS ANALYTICS</div><h2>Make progress visible.</h2><p>Strength, skills, consistency and body metrics are tracked separately.</p></div><button className="primary">Log measurement</button></div><div className="grid grid-4"><Stat label="STRENGTH" value="+18%" sub="12-week trend" icon={Dumbbell}/><Stat label="SKILLS" value="3 / 8" sub="milestones unlocked" icon={Target}/><Stat label="CONSISTENCY" value="87%" sub="weekly completion" icon={Activity}/><Stat label="SCORE" value="67" sub="not a medical metric" icon={Trophy}/></div><div className="section-title"><h3>Performance trends</h3><span>Relative progress</span></div><div className="grid grid-2"><div className="card"><div className="metric-top"><span>PUSH-UP REPS</span><span className="positive">15 max</span></div><div className="chart">{[32,39,45,48,56,62,59,70,73,81,88,95].map((h,i)=><span className="chart-bar" style={{height:`${h}%`}} key={i}/>)}</div><div className="chart-labels"><span>W1</span><span>W6</span><span>W12</span></div></div><div className="card"><div className="metric-top"><span>WEEKLY COMPLETION</span><span>87%</span></div><div className="chart">{[70,82,55,91,78,88,94,76,86,92,97,87].map((h,i)=><span className="chart-bar" style={{height:`${h}%`}} key={i}/>)}</div><div className="chart-labels"><span>W1</span><span>W6</span><span>W12</span></div></div></div><div className="section-title"><h3>Weekly report</h3><span>Latest complete week</span></div><div className="card"><div className="grid grid-4"><div><div className="metric-sub">WORKOUTS</div><b style={{fontSize:22}}>4</b></div><div><div className="metric-sub">COMPLETION</div><b style={{fontSize:22}}>87%</b></div><div><div className="metric-sub">PUSH-UPS</div><b style={{fontSize:22}}>+3</b></div><div><div className="metric-sub">PLANK</div><b style={{fontSize:22}}>+20s</b></div></div></div></>}

function Nutrition(){return <><div className="hero-row"><div><div className="eyebrow">NUTRITION</div><h2>Fuel the training.</h2><p>Targets are estimates and should adapt to actual progress rather than pretending to be exact.</p></div><button className="primary">Log meal</button></div><div className="grid grid-4"><Stat label="CALORIES" value="1,850" sub="of 2,200 estimate" icon={Utensils}/><Stat label="PROTEIN" value="105 g" sub="of 130 g target" icon={Activity}/><Stat label="WATER" value="2.2 L" sub="of 3.0 L target" icon={Activity}/><Stat label="MEALS" value="3 / 4" sub="logged today" icon={Check}/></div><div className="section-title"><h3>Today's meals</h3><span>Estimated values</span></div><div className="card">{[["Breakfast","Poha + curd + fruit","420 kcal · 16 g protein"],["Lunch","Roti + dal + sabzi","610 kcal · 27 g protein"],["Snack","Milk + roasted chana","290 kcal · 15 g protein"],["Dinner","Paneer/tofu + roti + vegetables","530 kcal · 42 g protein"]].map(m=><div className="exercise" style={{marginBottom:8}} key={m[0]}><div><div className="exercise-name">{m[0]} · {m[1]}</div><div className="exercise-meta">{m[2]}</div></div><ChevronRight size={15} color="var(--muted)"/></div>)}</div></>}

function Profile({onAssessment}:{onAssessment:()=>void}){return <><div className="hero-row"><div><div className="eyebrow">PROFILE & PREFERENCES</div><h2>Your training profile.</h2><p>Equipment, goals and preferences drive the plan generator.</p></div><button className="primary" onClick={onAssessment}>Run assessment</button></div><div className="grid grid-2"><div className="card"><div className="eyebrow">GOALS</div>{["Calisthenics skills","Strength","Fat loss / recomposition"].map(x=><div className="skill" key={x}><div className="skill-head"><b>{x}</b><Check size={15} color="var(--lime)"/></div></div>)}</div><div className="card"><div className="eyebrow">EQUIPMENT</div>{["Bodyweight","Dumbbells","Gym equipment","Pull-up station","Resistance bands"].map(x=><div className="skill" key={x}><div className="skill-head"><b>{x}</b><span>Available</span></div></div>)}</div></div><div className="section-title"><h3>Privacy & security</h3></div><div className="card"><div className="skill"><div className="skill-head"><b><ShieldCheck size={15}/> Private media by default</b><span>Enabled</span></div></div><div className="skill"><div className="skill-head"><b>AI video analysis</b><span>Optional</span></div></div><div className="skill"><div className="skill-head"><b>Export my data</b><ChevronRight size={15}/></div></div><div className="skill"><div className="skill-head"><b>Delete account</b><X size={15} color="var(--red)"/></div></div></div></>}

function Assessment({onClose,onDone}:{onClose:()=>void;onDone:()=>void}){const [step,setStep]=useState(1);const [goal,setGoal]=useState("Calisthenics skills");return <div style={{position:"fixed",inset:0,zIndex:100,background:"rgba(0,0,0,.72)",display:"grid",placeItems:"center",padding:16}}><div className="card" style={{width:"min(680px,100%)",maxHeight:"90vh",overflow:"auto",background:"#111419"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"start"}}><div><div className="eyebrow">FITNESS ASSESSMENT · {step}/3</div><h3 style={{fontSize:28,margin:"5px 0"}}>Build your training profile.</h3></div><button className="icon-btn" onClick={onClose}><X size={17}/></button></div>{step===1&&<div style={{marginTop:24}}><p style={{color:"var(--muted)",fontSize:13}}>What is your primary goal?</p><div className="grid grid-2">{["Calisthenics skills","Strength","Fat loss","Recomposition","General fitness","Conditioning"].map(g=><button key={g} onClick={()=>setGoal(g)} style={{textAlign:"left",padding:16,borderRadius:12,border:`1px solid ${goal===g?"var(--lime)":"var(--line)"}`,background:goal===g?"rgba(201,255,77,.08)":"var(--panel)",color:"var(--text)"}}>{g}</button>)}</div></div>}{step===2&&<div style={{marginTop:24}}><p style={{color:"var(--muted)",fontSize:13}}>What equipment do you have?</p><div className="grid grid-2">{["Bodyweight","Dumbbells","Barbell","Cable machine","Pull-up bar","Dip station","Resistance bands","Rings"].map(g=><button key={g} style={{textAlign:"left",padding:16,borderRadius:12,border:"1px solid var(--line)",background:"var(--panel)",color:"var(--text)"}}><Check size={15} color="var(--lime)"/> {g}</button>)}</div></div>}{step===3&&<div style={{marginTop:24}}><p style={{color:"var(--muted)",fontSize:13}}>Baseline tests are optional. “Can't perform” is different from 0 reps.</p>{["Push-ups","Squats","Plank","Pull-ups","Dead hang","Dips"].map(x=><div className="exercise" key={x}><span className="exercise-name">{x}</span><span className="chip">Not tested</span></div>)}</div>}<div style={{display:"flex",justifyContent:"space-between",marginTop:24}}><button className="icon-btn" onClick={()=>step>1&&setStep(step-1)}>{step>1?<ChevronRight size={16} style={{transform:"rotate(180deg)"}}/>:<X size={16}/>}</button>{step<3?<button className="primary" onClick={()=>setStep(step+1)}>Continue</button>:<button className="primary" onClick={onDone}>Generate my plan <Sparkles size={15}/></button>}</div></div></div>}

function Coach({onClose}:{onClose:()=>void}){const [message,setMessage]=useState("");const [sent,setSent]=useState(false);return <div style={{position:"fixed",right:20,bottom:20,zIndex:90,width:"min(410px,calc(100% - 32px))",border:"1px solid var(--line)",borderRadius:18,background:"#111419",boxShadow:"0 25px 80px rgba(0,0,0,.5)",overflow:"hidden"}}><div style={{padding:16,borderBottom:"1px solid var(--line)",display:"flex",justifyContent:"space-between"}}><div><b>AI Coach</b><small style={{display:"block",color:"var(--muted)",marginTop:2}}>Context-aware training assistant</small></div><button className="icon-btn" onClick={onClose}><X size={15}/></button></div><div style={{padding:16}}><div className="coach-message"><div className="coach-icon"><Sparkles size={16}/></div><p><strong>{sent?"Based on your plan:":"Coach"}</strong> {sent?"keep the next session focused on clean reps and controlled progression. If your technique degrades, reduce the load or regress the movement.":"Ask about today's workout, exercise substitutions, progression or recovery."}</p></div><div style={{display:"flex",gap:8,marginTop:16}}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Why am I not improving?" style={{flex:1,minWidth:0,background:"#0b0d10",border:"1px solid var(--line)",borderRadius:10,padding:"10px 12px",color:"white",outline:"none"}}/><button className="primary" onClick={()=>{setSent(true);setMessage("")}}>Ask</button></div></div></div>}
